@ThreeMorons_HostAddress = https://localhost:7174

GET {{ThreeMorons_HostAddress}}/

###

POST {{ThreeMorons_HostAddress}}/user/authorize

###

POST {{ThreeMorons_HostAddress}}/user/register
Content-Type: application/json

{
  "login": "olga22",
  "password": "asd123"
}
###

GET {{ThreeMorons_HostAddress}}/user/

###

POST {{ThreeMorons_HostAddress}}/user/authorize
Content-Type: application/json

{   
    "login": "TestLev228",
    "password": "Ce[fhbrb2404"
}

###
