@ThreeMorons_HostAddress = https://localhost:7174

GET {{ThreeMorons_HostAddress}}/

###

GET {{ThreeMorons_HostAddress}}/

###

POST {{ThreeMorons_HostAddress}}/register
Content-Type: application/json

{
  "login": "testpidor",
  "password": "TestoviyPidor22!",
  "name": "Амонгус",
  "surname": "тигрилов",
  "patronymic": "саваннович",
  "UserClassId": 2
}
###


GET {{ThreeMorons_HostAddress}}/SecretInfoTest 

###

POST {{ThreeMorons_HostAddress}}/authorizeTest
Content-Type: application/json

{
    "login": "sobaka123",
    "password": "Ce[fhbrb2404"
}
###
