@ThreeMorons_HostAddress = https://localhost:7174

GET {{ThreeMorons_HostAddress}}/

###

GET {{ThreeMorons_HostAddress}}/

###

POST {{ThreeMorons_HostAddress}}/register
Content-Type: application/json

{
  "login": "sasasasa",
  "password": "Ce[fhbrb2404",
  "name": "Амонгус",
  "surname": "тигрилов",
  "patronymic": "саваннович",
  "UserClassId": 1
}
###

